version: '3.7'

services:
    # backend
    backend:
        container_name: tapgives_api
        build: ./backend
        command: bash -c "sh ./prestart.sh"
        volumes:
            - ./backend/:/app/
        ports:
            - "${BACKEND_PORT}:80"
        env_file:
            - .env
        depends_on:
            - ${POSTGRES_SERVER}
            # - cache
    
    # database
    tapgives_db:
        container_name: tapgives_db
        image: postgres:alpine
        volumes:
            - data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGPORT=${POSTGRES_PORT}
        ports:
            - "${POSTGRES_PORT}:5436"
        # restart: "on-failure:5"
        

     # ui interfaces

    frontend:
        container_name: frontend
        build: ./frontend
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - "${WEB_PORT}:8081"
        environment:
            - CHOKIDAR_USEPOLLING=true
    # frontend:
    #     container_name: frontend
    #     build: ./frontend
    #     restart: "always"

    # frontend-web:
    #     container_name: frontendweb
    #     build: ./frontend/nginx
    #     ports:
    #         - "${WEB_PORT}:8081"
    #     restart: "always"
    # cache
    # cache:
    #     container_name: tapgives_rds
    #     image: redis:alpine
    #     ports:
    #         - "${REDIS_PORT}:6380"
    #     restart: "always"

volumes:
  data: