version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
      - curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      - chmod +x /usr/local/bin/lightsailctl
  pre_build:
    commands:
      ## CONFIGURE THIS: Repo name, please make sure this repo exists in ECR
      - export IMAGE_REPO_NAME=apibackend
      - export LATEST_TAG=latest
      - export VERSION_TAG=$(date '+%Y%m%d%H%M')

      ## Get AWS Account Id
      - export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d':' -f 5)


  build:
    commands:
      ## Moving to backend folder
      - cd api/
      - cp .env.example .env

      ## Build docker image
      - docker-compose -f compose.yml build

  post_build:
    commands:
      ## Push Docker Image
      - aws lightsail push-container-image --region $AWS_DEFAULT_REGION --service-name tapgives --label $IMAGE_REPO_NAME --image $IMAGE_REPO_NAME:$LATEST_TAG

      ## Update the service with the new image
      - printf '{"ImageURI":"%s:%s"}' $IMAGE_REPO_NAME $LATEST_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json