version: '3.7'


services:
    # backend
    backend:
        container_name: tapgives_api
        build: ./backend
#        command: bash -c "sh ./prestart.sh"
        image: api_backend:latest
        volumes:
            - ./backend/:/app/
        ports:
            - "80:80"
        env_file:
            - .env