version: '3.7'

services:
  user_service:
    build: ./user-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./user-service/:/app/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET=${SECRET}
    depends_on:
      - db

  project_service:
    build: ./project-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./project-service/:/app/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET=${SECRET}
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:5432"

  nginx:
    image: nginx:latest
    ports:
      - "${WEB_PORT}:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - project_service

volumes:
  data: